### ISSUE TITLE
Some buttons don't work if they're clicked outside the text

### ISSUE THREAD

**Issue by cvirostek** [CSC307Winter2019/FantasticFive#102]
For example: clicking on the edges of the Employee Login button outside the text doesn't register. Also applies to buttons on the Orders page, Inventory page, etc.

Expected: clicking anywhere on a button will register a click.

**Comment by mfekadu** [comment]
ohhh, interesting! @jlfisher, do you think this is this because of router-link?

![clicking](https://user-images.githubusercontent.com/11131250/53785525-9923f880-3ecd-11e9-8820-ecda9523576d.gif)

**Comment by jlfisher** [comment]
I think this is just a problem with Bulma buttons because I can replicate the issue on [their official website](https://bulma.io/documentation/elements/button/) too. We can ask professor if he knows a solution though.
