### ISSUE TITLE
Order status doesn't immediately update after changing it

### ISSUE THREAD

**Issue by cvirostek** [CSC307Winter2019/FantasticFive#104]
You have to leave the Orders page and switch back for changes to be reflected.

Expected: the order status will show the new status right after clicking Save.

**Comment by mfekadu** [comment]
thanks @cvirostek! 

@ztwestfall, I think @jlfisher knows how to make this work using the `.then({...})` syntax, right?

here's a gif: 

![order_status](https://user-images.githubusercontent.com/11131250/53787710-95e03b00-3ed4-11e9-93d2-e57cc640f0b0.gif)
