### ISSUE TITLE
Services on employee side don't show description

### ISSUE THREAD

**Issue by KaitlinBleich** [CSC307Winter2019/FantasticFive#105]

**Comment by mfekadu** [comment]
thanks @KaitlinBleich!

While the title is true, I am not sure this issue is a bug? 

@jlfisher, what do you think?

![image](https://user-images.githubusercontent.com/11131250/53787936-29197080-3ed5-11e9-9c6c-335e7131772d.png)

**Comment by jlfisher** [comment]
I don't think we need to show description for services and announcements because they could be very long. The title should be enough to differentiate each one.

**Comment by mfekadu** [comment]
sounds good, I agree!
