### ISSUE TITLE
No error message when creating/updating a user with a non-unique username

### ISSUE THREAD

**Issue by cvirostek** [CSC307Winter2019/FantasticFive#106]
Expected: the page should display an error when trying to do this.

**Comment by mfekadu** [comment]
# thanks @cvirostek!

seems like a quick UI enhancement. @jlfisher would you like to update this? 

# Here is a gif:
![no_err](https://user-images.githubusercontent.com/11131250/53788697-5e26c280-3ed7-11e9-9e45-14c07b45c046.gif)

# here is a screenshot of the Console error:
![image](https://user-images.githubusercontent.com/11131250/53788714-65e66700-3ed7-11e9-955c-2531b1d228ea.png)

# Here is the console text:
```
POST http://localhost:3000/users 500 (Internal Server Error)

createError.js?2d83:16 Uncaught (in promise) Error: Request failed with status code 500
    at createError (createError.js?2d83:16)
    at settle (settle.js?467f:18)
    at XMLHttpRequest.handleLoad (xhr.js?b50d:77)
createError @ createError.js?2d83:16
settle @ settle.js?467f:18
handleLoad @ xhr.js?b50d:77
Promise.then (async)
addUser @ EmployeeEdit.vue?d494:72
invoker @ vue.runtime.esm.js?2b0e:2132
fn._withTask.fn._withTask @ vue.runtime.esm.js?2b0e:1917
```

**Comment by mfekadu** [comment]
marked as a bug because of the 500 (internal server error) since ideally, that could be avoided

**Comment by jlfisher** [comment]
Yeah that should be a pretty easy fix. I'll get on it
