### ISSUE TITLE
No server-side check to make sure a user is an employee when performing employee tasks

### ISSUE THREAD

**Issue by cvirostek** [CSC307Winter2019/FantasticFive#107]
Expected: a malicious person should not be able to call the API without being logged in

**Comment by mfekadu** [comment]
@cvirostek, I am unable to reproduce this issue. What were your steps to discover this security vulnerability?

**Comment by jlfisher** [comment]
Maybe this is referring to being able to make changes to the DB through Postman without verification? But I believe we only have to protect the frontend and not the backend.

**Comment by mfekadu** [comment]
solution is to guard the api with a token, but this is a nice to have according to the client
