### ISSUE TITLE
Employee can add a Product to the store

### ISSUE THREAD

**Issue by mfekadu** [CSC307Winter2019/FantasticFive#79]

**Comment by mfekadu** [comment]
Is it really just Admin (not Employee) who has this privilege? @jkrisfox

**Comment by jkrisfox** [comment]
No this is any employee.

On Feb 13, 2019, at 3:49 PM, Michael Fekadu <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it really just Admin (not Employee) who has this privilege? @jkrisfox<https://github.com/jkrisfox>
